spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: central-station-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false  # Disable auto-commit for manual acknowledgment
    listener:
      ack-mode: manual # manual ack for when parquet is written successfully
server:
  port: 8080

bitcask:
  storage-path: ./data/bitcask

parquet:
  storage-path: ./data/parquet
  batch-size: 10000
